// import {Geist, Geist_Mono} from "next/font/google"
import Script from "next/script";
import { ArticleProvider } from "@/hooks/use-articleOld";
import { AuthProvider } from "@/hooks/use-auth";
// import "@/styles/basic.css";
// import "@/styles/reset.css";
import "@/styles/globalsHui.css"
import Header from "./_components/header";
import Footer from "./_components/footer"
import { CartProvider } from "@/hooks/use-cart";
import 'bootstrap-icons/font/bootstrap-icons.css';
import RootHeader from './_components/RootHeader';
// import { CartProvider } from './contexts/CartContext.js';
import BackToTop from '@/app/products/_components/BackToTop';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          rel="stylesheet"
        />
        <script src="https://cdn.jsdelivr.net/npm/gsap@3.13.0/dist/gsap.min.js"></script>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
      </head>
      <body>
        <AuthProvider>
          <CartProvider>
            <ArticleProvider>
              <RootHeader />
              {children}
              <ToastContainer position="top-center" autoClose={2000} hideProgressBar={true} closeOnClick />
              <BackToTop />
              <Footer />
            </ArticleProvider>
          </CartProvider>
        </AuthProvider>
      </body>

    </html>
  );
}
