// import {Geist, Geist_Mono} from "next/font/google"
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";
import { ArticleProvider } from "@/hooks/use-article";
import "bootstrap/dist/css/bootstrap.min.css";
// import "@/styles/basic.css";
// import "@/styles/reset.css";
import "@/styles/globalsHui.css"
import Header from "./_components/header";
import Footer from "./_components/footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          rel="stylesheet"
        />

        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
      </head>
      <ArticleProvider>
        <body>
          <Header />
          {children}
           <Footer />
        </body>
      </ArticleProvider>
     
    </html>
  );
}
